### PR TITLE
Move controllers to OOP

### PR DESCRIPTION
**Pull request by dwill21**
Move the collection of functions comprising the controllers into respective classes.

### CODE REVIEW

**Comment by fredlawl** [comment]
Sorry for taking so long on this. I ran the test suite on Monday and that ran OKAY. I'm going to do a full-on test with Paw sometime later this week, and then hopefully merge this in :)

**Comment by fredlawl** [comment]
@dwill21 I got around to finally testing this. There was a pretty big issue that happened such that the URLs were not exactly being mapped correctly to the controller functions. This results in 500 page error codes. I can take over this from here to make the necessary updates if you don't mind.

**Comment by dwill21** [comment]
@fredlawl Sounds good. I'll be curious to see what the issue was once you're done.

**Comment by fredlawl** [comment]
@dwill21 I think I'm going to table this pull request for now. We're having some internal debate atm as to wether we should go through with this still.

**Pull request closed without merging**
